server {
    listen 80;
    root /usr/share/nginx/html/admin;
    index index.html;
    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
    client_max_body_size 25M;
    location / {
        try_files $uri $uri/ /index.html;
    }
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}
